### ISSUE TITLE
Branch feature/gpg-vks: ImportError: cannot import name 'NoKeyResponse'

### ISSUE THREAD

**Issue by vollkorn1982** [Selfnet/hkp4py#19]
Took me a while to get around to test vks support, but today I wanted to do so, but failed at importing the hkp4py package when checking out the branch feature/gpg-vks.

```
>>> import hkp4py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/Projekte/hkp4py/hkp4py/__init__.py", line 4, in <module>
    from .client import HKPClient, HKPClient as KeyServer
  File "/home/jan/Projekte/hkp4py/hkp4py/client.py", line 5, in <module>
    from .exceptions import MalformedURL, UnsupportedProtocol
  File "/home/jan/Projekte/hkp4py/hkp4py/exceptions.py", line 1, in <module>
    from .protocols import Protocol
  File "/home/jan/Projekte/hkp4py/hkp4py/protocols/__init__.py", line 4, in <module>
    from .vks import VKSKey
  File "/home/jan/Projekte/hkp4py/hkp4py/protocols/vks.py", line 5, in <module>
    from ..exceptions import NoKeyResponse
ImportError: cannot import name 'NoKeyResponse'
```
This works:
1. git clone https://github.com/Selfnet/hkp4py.git
1. python3
1. import hkp4py

This does not work:
1. git clone https://github.com/Selfnet/hkp4py.git
1. git checkout feature/gpg-vks
1. python3
1. import hkp4py

**Comment by Cellebyte** [comment]
Cool will fix that.

**Comment by Cellebyte** [comment]
@vollkorn1982 please try again.
